// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaManagerProg5.DbAccess;

#nullable disable

namespace NinjaManagerProg5.Migrations
{
    [DbContext(typeof(MyNinjaDbContext))]
    [Migration("20241030102754_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaManagerProg5.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoldValue")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 3,
                            Category = "Hand",
                            GoldValue = 50,
                            Intelligence = 0,
                            Name = "Sword",
                            Strength = 5
                        },
                        new
                        {
                            Id = 2,
                            Agility = 0,
                            Category = "Head",
                            GoldValue = 30,
                            Intelligence = 1,
                            Name = "Helmet",
                            Strength = 2
                        },
                        new
                        {
                            Id = 3,
                            Agility = 2,
                            Category = "Chest",
                            GoldValue = 80,
                            Intelligence = 0,
                            Name = "Armor",
                            Strength = 10
                        });
                });

            modelBuilder.Entity("NinjaManagerProg5.Models.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ninja");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gold = 100,
                            Name = "Ninja A"
                        },
                        new
                        {
                            Id = 2,
                            Gold = 150,
                            Name = "Ninja B"
                        });
                });

            modelBuilder.Entity("NinjaManagerProg5.Models.NinjaEquipment", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("NinjaId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("NinjaEquipments");
                });

            modelBuilder.Entity("NinjaManagerProg5.Models.NinjaEquipment", b =>
                {
                    b.HasOne("NinjaManagerProg5.Models.Equipment", "Equipment")
                        .WithMany("NinjaEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaManagerProg5.Models.Ninja", "Ninja")
                        .WithMany("NinjaEquipments")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaManagerProg5.Models.Equipment", b =>
                {
                    b.Navigation("NinjaEquipments");
                });

            modelBuilder.Entity("NinjaManagerProg5.Models.Ninja", b =>
                {
                    b.Navigation("NinjaEquipments");
                });
#pragma warning restore 612, 618
        }
    }
}
